### ISSUE TITLE
it stops execution if the channel is 404

### ISSUE THREAD

**Issue by fishky** [jeb5/YouTube-Subscriptions-RSS#2]
<img width="448" alt="Snipaste_2023-06-17_12-53-56" src="https://github.com/jeb5/YouTube-Subscriptions-RSS/assets/7286495/0ff664b3-20c4-4e61-91b8-fb25f2932128">
<img width="1049" alt="Snipaste_2023-06-17_12-53-38" src="https://github.com/jeb5/YouTube-Subscriptions-RSS/assets/7286495/9c7a9d6d-1e75-4c9b-a31d-d17358bb9b2d">

**Comment by jeb5** [comment]
Good catch.

Looks like there's something strange going on with the BBC's Chinese channel. Not sure how to work around this, but I've updated the script to just skip channels that 404.
