### ISSUE TITLE
Parsing error with auto-generated YouTube Music channels

### ISSUE THREAD

**Issue by FelixLisczyk** [jeb5/YouTube-Subscriptions-RSS#3]
First of all, thank you for the great script! It helped me a lot.

When you follow an artist on YouTube Music who doesn't have his own YouTube channel, YT automatically creates a topic channel for the artist. Here is an example:

https://www.youtube.com/channel/UCZLrcCdfVC6gCQvADhSSWuQ

I've noticed that the script fails with the following error when it encounters one of these channels: `TypeError: Cannot read properties of null (reading '1')`

I assume that topic channels don't have their own RSS feed. Would it be possible to skip them in the script?

**Comment by jeb5** [comment]
Good catch. Thanks

Topic channels *do* appear to also generate RSS feeds, but they're missing usernames. I updated the script, so topic channels should work now.

**Comment by FelixLisczyk** [comment]
It works, thank you! 👍
