### ISSUE TITLE
OPML files are invalid

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [jeb5/YouTube-Subscriptions-RSS#4]
Tried importing them in Thunderbird and Akregator and it doesn't work. I think it has something to do with the feed putting everything in a single line. I tried fixing that with a simple beautify method but that didn't fix the issue. I have 1500 subscriptions so maybe that might be why.

**Comment by jeb5** [comment]
I've updated the script to remove the superfluous "title" attributes, and added line breaks, although I'd be surprised if the lack of line breaks was causing a problem for parsers.

The generated OPML file imports fine into Thunderbird for me, but I have 10x fewer subscriptions than you, so I wonder if Thunderbird does have an issue with too many feeds being imported.

You could also try [uploading](https://file.io) the OPML file and [validating it](http://validator.opml.org/).

**Comment by hexadezi** [comment]
Just add the encoding and it will work


\<?xml version="1.0" encoding="UTF-8"?>

This could be fixed in the script.

**Comment by jeb5** [comment]
Done, thanks for the tip.

**Comment by CoWinkKeyDinkInc** [comment]
> You could also try [uploading](https://file.io/) the OPML file and [validating it](http://validator.opml.org/).

Finally got around to trying this and it was an XML error arising from a channel name using `&` in it (`text="Wallace & Gromit"` for example). I replaced this with `&amp;` escape character and it works fine and displays correctly on Thunderbird. Please reopen this issue as it's still creating invalid XML.

Thank you for fixing the formatting btw :-)

**Comment by jeb5** [comment]
Cool, looks like the same problem as #7. I'll get on to this.

**Comment by jeb5** [comment]
Should be fixed. Let me know if you're still having problems
