### ISSUE TITLE
Does not load all subscriptions if there are over 100

### ISSUE THREAD

**Issue by sandorex** [jeb5/YouTube-Subscriptions-RSS#8]
Great script, thank you!
Just please put a disclaimer or automate scrolling down to the very bottom so all channels are loaded otherwise only first 100 will be saved and the user may not know if they have 102 channels

**Comment by jeb5** [comment]
Auto-scroll is a cool idea. Added!

Let me know if it works for you

**Comment by sandorex** [comment]
I just tried it and it works great!
