### ISSUE TITLE
VM1799:36 This document requires 'TrustedHTML' assignment.

### ISSUE THREAD

**Issue by alabotski** [jeb5/YouTube-Subscriptions-RSS#9]
Everything worked before. Now an error appears.
```
TypeError: Failed to execute 'parseFromString' on 'DOMParser': This document requires 'TrustedHTML' assignment.
    at <anonymous>:36:44

```

![image](https://github.com/user-attachments/assets/012538d3-9894-4bfe-9e4f-dd5bff08e77b)

**Comment by jeb5** [comment]
Thanks for letting me know! 😁

Looks like this is an issue on all Chromium-based browsers. I've implemented a quick fix, and everything should work in the latest commit. Please let me know if you have any more problems.

**Comment by alabotski** [comment]
![image](https://github.com/user-attachments/assets/18120680-1da7-4437-bbb8-a1bb437e3c23)
Error present

**Comment by alabotski** [comment]
Seems you don't update bookmark code?

**Comment by jeb5** [comment]
I did update the bookmarklet code--are you sure you're using the latest bookmarklet?
